"""
pdf_report.py -- Generates a polished, letterhead-style PDF Intelligence
Report per flagged ring. This is the deployment-grade counterpart to the
in-app markdown report and the CSV evidence export.

Uses reportlab (Platypus) -- see /mnt/skills/public/pdf/SKILL.md guidance:
never use unicode currency/subscript glyphs with built-in fonts, so amounts
are written as "Rs X" rather than the rupee sign.
"""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)


def build_intelligence_report_pdf(alert_row, ring_complaints, investigator_name: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=1.8 * cm, bottomMargin=1.8 * cm,
        leftMargin=2 * cm, rightMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Title"], fontSize=18, textColor=colors.HexColor("#0f172a"),
    )
    agency_style = ParagraphStyle(
        "Agency", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#475569"),
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], fontSize=12, textColor=colors.HexColor("#0f172a"),
        spaceBefore=14, spaceAfter=6,
    )
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=14)

    story = []

    # --- Letterhead ---
    story.append(Paragraph("PredictGuard", title_style))
    story.append(Paragraph(
        "Predictive Analytics Framework for Cybercrime Cash-Withdrawal Location Forecasting "
        "&mdash; SIH26184 &mdash; Indian Cyber Crime Coordination Centre (I4C)",
        agency_style,
    ))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1")))
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"INTELLIGENCE REPORT &mdash; {alert_row['ring_id']}", section_style))

    header_table_data = [
        ["Alert ID", alert_row["alert_id"]],
        ["Ring ID", alert_row["ring_id"]],
        ["Predicted withdrawal location", alert_row["predicted_location"]],
        ["Predicted time window", alert_row["predicted_time_window"]],
        ["Risk score", f"{alert_row['risk_score']:.2f}"],
        ["Report generated", datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
        ["Generated by (LEA login)", investigator_name],
    ]
    header_table = Table(header_table_data, colWidths=[6.5 * cm, 9 * cm])
    header_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#475569")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#e2e8f0")),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 10))

    # --- Ring summary ---
    total_amount = ring_complaints["amount"].sum()
    account_count = ring_complaints["account_id"].nunique()
    crime_types = ring_complaints["crime_type"].value_counts().to_dict()
    crime_breakdown = ", ".join(f"{k}: {v}" for k, v in crime_types.items())
    date_min = ring_complaints["timestamp"].min()
    date_max = ring_complaints["timestamp"].max()

    story.append(Paragraph("Ring Summary", section_style))
    summary_text = (
        f"Linked accounts involved: <b>{account_count}</b><br/>"
        f"Total complaint amount linked to this ring: <b>Rs {total_amount:,.2f}</b><br/>"
        f"Complaint activity window: <b>{date_min}</b> to <b>{date_max}</b><br/>"
        f"Crime type breakdown: {crime_breakdown}"
    )
    story.append(Paragraph(summary_text, body_style))
    story.append(Spacer(1, 10))

    # --- Evidence table ---
    story.append(Paragraph("Evidence Documentation", section_style))
    evidence_cols = ["complaint_id", "account_id", "linked_account_id", "amount", "crime_type", "city"]
    table_data = [["Complaint ID", "Account", "Linked Account", "Amount (Rs)", "Crime Type", "City"]]
    for _, row in ring_complaints[evidence_cols].iterrows():
        table_data.append([
            row["complaint_id"], row["account_id"], row["linked_account_id"] or "-",
            f"{row['amount']:,.0f}", row["crime_type"], row["city"],
        ])

    evidence_table = Table(table_data, repeatRows=1, colWidths=[2.6 * cm, 2.2 * cm, 2.4 * cm, 2.2 * cm, 2.8 * cm, 2.8 * cm])
    evidence_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7.5),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(evidence_table)
    story.append(Spacer(1, 12))

    # --- Recommended action ---
    story.append(Paragraph("Recommended Action", section_style))
    story.append(Paragraph(
        f"Deploy field verification unit near <b>{alert_row['predicted_location']}</b> within the "
        f"predicted window. Cross-check linked accounts against CFCFRMS for any pending freeze "
        f"requests before approaching for physical intervention.",
        body_style,
    ))
    story.append(Spacer(1, 20))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1")))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "This report was generated by PredictGuard, a prototype predictive analytics system. "
        "Not for evidentiary use without independent verification.",
        agency_style,
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
